language: sh

sudo: required

before_install:
  - sudo curl -Lso /usr/bin/shellcheck https://github.com/caarlos0/shellcheck-docker/releases/download/v0.4.6/shellcheck
  - sudo chmod +x /usr/bin/shellcheck

script:
 - shellcheck -s bash test.sh

matrix:
fast_finish: true
